# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "db628c87e4ac299fcdfa490056b32c8d"
application_url = "https://app-daniel-roa-649998503509.us-central1.run.app"
embedded = true
name = "app-daniel-roa"

[webhooks]
api_version = "2026-10"

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/uninstalled"
  topics = [ "app/uninstalled" ]

  [[webhooks.subscriptions]]
  uri = "/webhooks/app/scopes_update"
  topics = [ "app/scopes_update" ]

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_products"

[auth]
redirect_urls = [ "https://app-daniel-roa-649998503509.us-central1.run.app/auth/callback", "https://app-daniel-roa-649998503509.us-central1.run.app/auth/login", "https://app-daniel-roa-649998503509.us-central1.run.app/api/auth" ]

[build]
include_config_on_deploy = true
automatically_update_urls_on_dev = true
